### ISSUE TITLE
Install Issue?

### ISSUE THREAD

**Issue by msj121** [Anush008/fastembed-go#8]
I get the following error: 
`github.com/yalue/onnxruntime_go: build constraints exclude all Go files in C:\Users\ME\go\pkg\mod\github.com\yalue\onnxruntime_go@v1.7.0`

I have windows, do I need to install something else to get this to work?

**Comment by Anush008** [comment]
No additional steps should be necessary.

**Comment by Anush008** [comment]
Maybe this thread could help for Windows.

https://stackoverflow.com/questions/55348458/build-constraints-exclude-all-go-files-in

**Comment by Anush008** [comment]
Additionally, if you run into this common issue

https://github.com/Anush008/fastembed-go?tab=readme-ov-file#%E2%84%B9%EF%B8%8E-notice

**Comment by msj121** [comment]
If anyone needs help, in the cmd or perhaps environment variables you need to set CGO_ENABLED=1. Also gcc needs to be setup. I used mingw. Simply download the folder and point gcc environment variable to the bin folder, point being so typing gcc in terminal will get you the gcc compiler.

Thanks for your help
