### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by msj121** [Anush008/fastembed-go#9]
Looking through the code I didn't see a setting for using Cuda/GPU, is this done automatically, or is there a setting? Tried looking in the Onnx project, but got a little confused.

Thanks.

**Comment by Anush008** [comment]
Hi. We could configure GPU, like FastEmbed for other languages. But since I don't have access to a GPU instance, I can't verify it. If you do, please consider contributing.

**Comment by Anush008** [comment]
Hi. We could add a configuration option for GPU, like FastEmbed for the other languages. But since I don't have access to a GPU instance, I can't verify it. If you do, please consider contributing.

**Comment by msj121** [comment]
Ok - I do have indirect access to a computer with a gpu. Let me try and look around the code etc... If you have any advice lmk.

**Comment by Anush008** [comment]
There's an execution providers option.
https://github.com/Anush008/fastembed-go/blob/bbcc4da928d23eea76be309148ad1d298b9c23af/fastembed.go#L61 that is not being used.

You'd need to verify if we can pass and make it work with CUDA for example. We're using https://github.com/yalue/onnxruntime_go to interface with ONNX.

**Comment by Anush008** [comment]
Probably would have to change the type of the option from `string[]` to the one used by [onnxruntime_go](https://github.com/yalue/onnxruntime_go) for execution providers.

**Comment by Anush008** [comment]
Closing since stale. Please feel free to re-open.
